#ifndef MODULEQUICKSORT_GLOBAL_H
#define MODULEQUICKSORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULEQUICKSORT_LIBRARY)
#  define MODULEQUICKSORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULEQUICKSORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULEQUICKSORT_GLOBAL_H
