#ifndef NODULEPRIM_GLOBAL_H
#define NODULEPRIM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NODULEPRIM_LIBRARY)
#  define NODULEPRIMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NODULEPRIMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NODULEPRIM_GLOBAL_H
