#ifndef MODULEPRIM_GLOBAL_H
#define MODULEPRIM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULEPRIM_LIBRARY)
#  define MODULEPRIMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULEPRIMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULEPRIM_GLOBAL_H
